services:
    wishibam.mondial_relay.form.shipping_method_type_extension:
        class: Wishibam\SyliusMondialRelayPlugin\Form\Extension\ShippingMethodChoiceTypeExtension
        public: false
        arguments:
            $shippingMethodsResolver: '@sylius.shipping_methods_resolver'
            $repository: '@sylius.repository.shipping_method'
            $configuration: '@wishibam_mondial_relay.parsed_configuration'
            $session: '@session'
        tags:
            - { name: 'form.type_extension' }

    wishibam.mondial_relay.serialization.shipment:
        class: Wishibam\SyliusMondialRelayPlugin\EventSubscriber\Serialization\JMS\ShipmentNormalizer
        arguments:
            $configuration: '@wishibam_mondial_relay.parsed_configuration'
        tags:
            - { name: 'jms_serializer.event_subscriber' }
