services:
    wishibam.mondial_relay.form.shipping_method_type_extension:
        class: Wishibam\SyliusMondialRelayPlugin\Form\Extension\ShippingMethodChoiceTypeExtension
        public: false
        arguments:
            $shippingMethodsResolver: '@sylius.shipping_methods_resolver'
            $repository: '@sylius.repository.shipping_method'
            $session: '@session'
            $dispatcher: '@event_dispatcher'
        tags:
            - { name: 'form.type_extension' }

    wishibam.mondial_relay.form.forget_previous_address:
        class: Wishibam\SyliusMondialRelayPlugin\Form\Extension\AddressTypeExtension
        public: false
        arguments:
            $session: '@session'
        tags:
            - { name: 'form.type_extension' }

    wishibam.mondial_relay.serialization.shipment:
        class: Wishibam\SyliusMondialRelayPlugin\EventSubscriber\Serialization\JMS\ShipmentNormalizer
        arguments:
            $configurationResolver: '@wishibam_mondial_relay.configuration_resolver'
        tags:
            - { name: 'jms_serializer.event_subscriber' }

    wishibam.mondial_relay.form.extension.shipping_method:
        arguments:
            $configurationResolver: '@wishibam_mondial_relay.configuration_resolver'
        class: Wishibam\SyliusMondialRelayPlugin\Form\Extension\ShippingMethodTypeExtension
        tags:
            - name: form.type_extension
              extended_type: Sylius\Bundle\ShippingBundle\Form\Type\ShippingMethodType

    wishibam.mondial_relay.twig_extension:
        arguments:
            $configurationResolver: '@wishibam_mondial_relay.configuration_resolver'
        class: Wishibam\SyliusMondialRelayPlugin\Twig\MondialRelayExtension
        tags:
            - { name: twig.extension }
